name: Latest Blog Post Workflow

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/muris11"
          max_post_count: 5
          template: "- [$title]($url)"
          date_format: "mmm dd, yyyy"
